version: '3.8'

services:
  app:
    container_name: some-webchat
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    volumes:
      - ./app/:/app/app
    ports:
      - 5000:5000
